/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Restaurant.Menu;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Restaurant restaurant;    
    private UserAccount userAccount;
    private EcoSystem ecosystem;
    ArrayList<Menu> items=new ArrayList<Menu>();
    int sum = 0;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public CustomerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecosystem, Restaurant restaurant) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAccount = account;
        this.restaurant = restaurant;
        
        populateCustTable();
       
    }
    
    public void populateCustTable(){
        DefaultTableModel tablemodel = (DefaultTableModel) tblRestMenu.getModel();
        
            tablemodel.setRowCount(0);
                Object[] row = new Object[3];
                for(Menu menu:restaurant.getMenu()){
                     row[0] = menu;
                     row[1] = menu.getDescription();
                     row[2] = menu.getPrice();
                     tablemodel.addRow(row);
                } 
        
    }
    
    public void populateCart(Menu dishitem){
        DefaultTableModel tablemodel = (DefaultTableModel) tblOrder.getModel();
        tablemodel.setRowCount(0);
        
         items.add(dishitem);
         Object[] row = new Object[4];
                for(Menu menu:items){
                     row[0] = menu;
                     row[1] = menu.getDescription();
                     row[2] = menu.getQuantity();
                     row[3] = menu.getPrice()*menu.getQuantity();
                    
                     sum=sum+(menu.getPrice()*menu.getQuantity());
                     tablemodel.addRow(row);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlaceOrder = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRestMenu = new javax.swing.JTable();
        btnAddToCart = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        btnRemoveFromCart = new javax.swing.JButton();
        txtAddressField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPlaceOrder.setBackground(new java.awt.Color(0, 255, 255));
        btnPlaceOrder.setForeground(new java.awt.Color(51, 0, 204));
        btnPlaceOrder.setText("Place Order!");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 130, 50));

        backJButton.setBackground(new java.awt.Color(0, 255, 255));
        backJButton.setForeground(new java.awt.Color(51, 0, 204));
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 130, 30));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Order Cart:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 110, 30));

        tblRestMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Dishes", "Description", "Price"
            }
        ));
        jScrollPane1.setViewportView(tblRestMenu);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, 90));

        btnAddToCart.setBackground(new java.awt.Color(0, 255, 255));
        btnAddToCart.setForeground(new java.awt.Color(51, 0, 204));
        btnAddToCart.setText("Add To Cart");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });
        add(btnAddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Dishes", "Description", "Quantity", "Price"
            }
        ));
        jScrollPane2.setViewportView(tblOrder);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, 90));

        btnRemoveFromCart.setBackground(new java.awt.Color(0, 255, 255));
        btnRemoveFromCart.setForeground(new java.awt.Color(51, 0, 204));
        btnRemoveFromCart.setText("Remove Item");
        btnRemoveFromCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFromCartActionPerformed(evt);
            }
        });
        add(btnRemoveFromCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));

        txtAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressFieldActionPerformed(evt);
            }
        });
        add(txtAddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 250, -1));

        jLabel1.setText("Enter Delivery Location:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 430, 130, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        String address=txtAddressField.getText();
        restaurant.addOrder(restaurant.getName(), userAccount.getUsername(), null, items, sum , address);
        for(Customer cust: ecosystem.getCustomerDirectory().getCustomerList()){
            if(userAccount.getUsername().equals(cust.getCustomerName())){
                cust.addOrder(restaurant.getName(), userAccount.getUsername(), null, items, sum , address);
                JOptionPane.showMessageDialog(null, "Order placed successfully");
            }
        }
        
        
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerAreaJPanel dwjp = (CustomerAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRestMenu.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table to add","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            Menu Item=(Menu)tblRestMenu.getValueAt(selectedRow, 0);

            populateCart(Item);

        }

    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void btnRemoveFromCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFromCartActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrder.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table to remove from cart","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            Menu item=(Menu)tblOrder.getValueAt(selectedRow, 0);
            items.remove(item);
            DefaultTableModel model = (DefaultTableModel) tblOrder.getModel();
            model.setRowCount(0);
            // commented no use
        }
    }//GEN-LAST:event_btnRemoveFromCartActionPerformed

    private void txtAddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnRemoveFromCart;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTable tblRestMenu;
    private javax.swing.JTextField txtAddressField;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
