/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.MedicalRecord;

/**
 *
 * @author rtspi
 */
public class CreateMedicalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateMedicalJPanel
     */
    MedicalRecord medicalRecord;
    
    public CreateMedicalJPanel(MedicalRecord medicalRecord) {
        initComponents();
        this.medicalRecord = medicalRecord;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        lblMedicalRecord = new javax.swing.JLabel();
        lblRecordNum = new javax.swing.JLabel();
        lblAllergy1 = new javax.swing.JLabel();
        lblAllergy2 = new javax.swing.JLabel();
        lblAllergy3 = new javax.swing.JLabel();
        txtMedicalRecordNum = new javax.swing.JTextField();
        txtAllergy1 = new javax.swing.JTextField();
        txtAllergy2 = new javax.swing.JTextField();
        txtAllergy3 = new javax.swing.JTextField();
        btnSaveMedical = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setPreferredSize(new java.awt.Dimension(500, 350));

        lblMedicalRecord.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblMedicalRecord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedicalRecord.setText("Medical Record");

        lblRecordNum.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblRecordNum.setText("Medical Record Number:");

        lblAllergy1.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblAllergy1.setText("Allergy 1:");

        lblAllergy2.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblAllergy2.setText("Allergy 2:");

        lblAllergy3.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblAllergy3.setText("Allergy 3:");

        txtMedicalRecordNum.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        txtMedicalRecordNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicalRecordNumActionPerformed(evt);
            }
        });

        txtAllergy1.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N

        txtAllergy2.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N

        txtAllergy3.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N

        btnSaveMedical.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        btnSaveMedical.setText("Save");
        btnSaveMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveMedicalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMedicalRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRecordNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAllergy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAllergy2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAllergy3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(70, 70, 70)))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAllergy3, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(txtAllergy2)
                    .addComponent(txtAllergy1)
                    .addComponent(txtMedicalRecordNum))
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(btnSaveMedical)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblMedicalRecord)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRecordNum)
                    .addComponent(txtMedicalRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAllergy1)
                    .addComponent(txtAllergy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAllergy2)
                    .addComponent(txtAllergy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAllergy3)
                    .addComponent(txtAllergy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnSaveMedical)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMedicalRecordNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicalRecordNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalRecordNumActionPerformed

    private void btnSaveMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveMedicalActionPerformed
        // TODO add your handling code here:
        
        medicalRecord.setMedicalRecordNum(txtMedicalRecordNum.getText());
        medicalRecord.setAllergy1(txtAllergy1.getText());
        medicalRecord.setAllergy2(txtAllergy2.getText());
        medicalRecord.setAllergy3(txtAllergy3.getText());

        JOptionPane.showMessageDialog(this, "Medical Record Information Saved");
    }//GEN-LAST:event_btnSaveMedicalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveMedical;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblAllergy1;
    private javax.swing.JLabel lblAllergy2;
    private javax.swing.JLabel lblAllergy3;
    private javax.swing.JLabel lblMedicalRecord;
    private javax.swing.JLabel lblRecordNum;
    private javax.swing.JTextField txtAllergy1;
    private javax.swing.JTextField txtAllergy2;
    private javax.swing.JTextField txtAllergy3;
    private javax.swing.JTextField txtMedicalRecordNum;
    // End of variables declaration//GEN-END:variables
}
