/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.SavingsAccountInformation;

/**
 *
 * @author rtspi
 */
public class CreateSavingsAccountJPanel extends javax.swing.JPanel {
    
    SavingsAccountInformation savingsAccInfo;
    /**
     * Creates new form CreateAccountJPanel
     */
    public CreateSavingsAccountJPanel(SavingsAccountInformation savingsAccInfo) {
        initComponents();
        this.savingsAccInfo = savingsAccInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblBankName1 = new javax.swing.JLabel();
        lblRoutingNum1 = new javax.swing.JLabel();
        lblAccountNum1 = new javax.swing.JLabel();
        lblAccountBal1 = new javax.swing.JLabel();
        lblAccountType1 = new javax.swing.JLabel();
        txtBankName1 = new javax.swing.JTextField();
        txtRoutingNum1 = new javax.swing.JTextField();
        txtAccountNum1 = new javax.swing.JTextField();
        txtAccountBal1 = new javax.swing.JTextField();
        txtAccountType1 = new javax.swing.JTextField();
        btnSaveSavings = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 350));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblTitle.setText("                                         Create Savings Account Information");

        lblBankName1.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblBankName1.setText("Bank Name:");

        lblRoutingNum1.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblRoutingNum1.setText("Routing Number:");

        lblAccountNum1.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblAccountNum1.setText("Account Number:");

        lblAccountBal1.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblAccountBal1.setText("Account Balance:");

        lblAccountType1.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblAccountType1.setText("Account Type:");

        txtBankName1.setBackground(new java.awt.Color(255, 255, 255));
        txtBankName1.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N

        txtRoutingNum1.setBackground(new java.awt.Color(255, 255, 255));
        txtRoutingNum1.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N

        txtAccountNum1.setBackground(new java.awt.Color(255, 255, 255));
        txtAccountNum1.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N

        txtAccountBal1.setBackground(new java.awt.Color(255, 255, 255));
        txtAccountBal1.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N

        txtAccountType1.setFont(new java.awt.Font("Calibri", 2, 11)); // NOI18N
        txtAccountType1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnSaveSavings.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        btnSaveSavings.setText("Save");
        btnSaveSavings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaveSavings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSavingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAccountType1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAccountType1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRoutingNum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBankName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(24, 24, 24)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAccountNum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(21, 21, 21))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAccountBal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAccountBal1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(txtAccountNum1)
                            .addComponent(txtBankName1)
                            .addComponent(txtRoutingNum1))))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(btnSaveSavings)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankName1)
                    .addComponent(txtBankName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoutingNum1)
                    .addComponent(txtRoutingNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountNum1)
                    .addComponent(txtAccountNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountBal1)
                    .addComponent(txtAccountBal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountType1)
                    .addComponent(txtAccountType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnSaveSavings)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveSavingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSavingsActionPerformed
        // TODO add your handling code here:
        savingsAccInfo.setBankName(txtBankName1.getText());
        savingsAccInfo.setAccountNum(txtAccountNum1.getText());
        savingsAccInfo.setAccountBal(txtAccountBal1.getText());
        savingsAccInfo.setRoutingNum(txtRoutingNum1.getText());
        savingsAccInfo.setAccountType(txtAccountType1.getText());
        
        
        JOptionPane.showMessageDialog(this, "Savings Account Information Saved");
    }//GEN-LAST:event_btnSaveSavingsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveSavings;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblAccountBal1;
    private javax.swing.JLabel lblAccountNum1;
    private javax.swing.JLabel lblAccountType1;
    private javax.swing.JLabel lblBankName1;
    private javax.swing.JLabel lblRoutingNum1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAccountBal1;
    private javax.swing.JTextField txtAccountNum1;
    private javax.swing.JTextField txtAccountType1;
    private javax.swing.JTextField txtBankName1;
    private javax.swing.JTextField txtRoutingNum1;
    // End of variables declaration//GEN-END:variables
}
