/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.DriversLicenseInfo;

/**
 *
 * @author rtspi
 */
public class CreateDriversLicenseJPanel extends javax.swing.JPanel {

    DriversLicenseInfo driversInfo;
    /**
     * Creates new form CreateDriversLicenseJPanel
     */
    public CreateDriversLicenseJPanel(DriversLicenseInfo driversInfo) {
        initComponents();
        this.driversInfo = driversInfo;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDriversLicense = new javax.swing.JLabel();
        lblLicenseNum = new javax.swing.JLabel();
        lblIssueDate = new javax.swing.JLabel();
        lblExpirationDate = new javax.swing.JLabel();
        lblBloodType = new javax.swing.JLabel();
        txtLicenseNum = new javax.swing.JTextField();
        txtIssueDate = new javax.swing.JTextField();
        txtExpirationDate = new javax.swing.JTextField();
        txtBloodType = new javax.swing.JTextField();
        btnSaveDrivers = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 350));

        lblDriversLicense.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblDriversLicense.setText("                                        Create Driver's License Information");

        lblLicenseNum.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblLicenseNum.setText("License Number:");

        lblIssueDate.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblIssueDate.setText("Issue Date:");

        lblExpirationDate.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblExpirationDate.setText("Expiration Date:");

        lblBloodType.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblBloodType.setText("Blood Type:");

        btnSaveDrivers.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        btnSaveDrivers.setText("Save");
        btnSaveDrivers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDriversActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDriversLicense, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLicenseNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIssueDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(26, 26, 26))
                            .addComponent(lblExpirationDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBloodType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(22, 22, 22)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtExpirationDate, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(txtIssueDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLicenseNum, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBloodType)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btnSaveDrivers)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblDriversLicense)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicenseNum)
                    .addComponent(txtLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIssueDate)
                    .addComponent(txtIssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExpirationDate))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBloodType)
                    .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSaveDrivers)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveDriversActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDriversActionPerformed
        // TODO add your handling code here:
        driversInfo.setLicenseNum(txtLicenseNum.getText());
        driversInfo.setIssueDate(txtIssueDate.getText());
        driversInfo.setExpirationDate(txtExpirationDate.getText());
        driversInfo.setBloodType(txtBloodType.getText());
        
        JOptionPane.showMessageDialog(this, "Driver's License Information Saved");
    }//GEN-LAST:event_btnSaveDriversActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveDrivers;
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblDriversLicense;
    private javax.swing.JLabel lblExpirationDate;
    private javax.swing.JLabel lblIssueDate;
    private javax.swing.JLabel lblLicenseNum;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JTextField txtExpirationDate;
    private javax.swing.JTextField txtIssueDate;
    private javax.swing.JTextField txtLicenseNum;
    // End of variables declaration//GEN-END:variables
}
