/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import javafx.scene.control.SplitPane;
import model.SavingsAccountInformation;
import model.Address;
import model.CheckingAccountInformation;
import model.DemographicInfo;
import model.DriversLicenseInfo;
import model.MedicalRecord;

/**
 *
 * @author rtspi
 */
public class MainJFrame extends javax.swing.JFrame {
    
    DemographicInfo demo;
    Address address;
    SavingsAccountInformation accInfo;
    DriversLicenseInfo driversInfo;
    MedicalRecord medicalRecord;
    SavingsAccountInformation savingsAccInfo;
    CheckingAccountInformation checkingAccInfo;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        demo = new DemographicInfo();
        address = new Address();
        accInfo = new SavingsAccountInformation();
        driversInfo = new DriversLicenseInfo();
        medicalRecord = new MedicalRecord();
        savingsAccInfo = new SavingsAccountInformation();
        checkingAccInfo = new CheckingAccountInformation();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnViewAccount1 = new javax.swing.JButton();
        btnViewDemo1 = new javax.swing.JButton();
        btnViewLicense1 = new javax.swing.JButton();
        lblMedicalRecord1 = new javax.swing.JLabel();
        lblDriversLicense1 = new javax.swing.JLabel();
        lblAddress1 = new javax.swing.JLabel();
        btnViewMedicalRecord1 = new javax.swing.JButton();
        btnCreateAddress1 = new javax.swing.JButton();
        btnCreateAccount1 = new javax.swing.JButton();
        lblAccountInfo1 = new javax.swing.JLabel();
        btnCreateLicense1 = new javax.swing.JButton();
        btnCreateMedicalRecord1 = new javax.swing.JButton();
        btnViewAddress1 = new javax.swing.JButton();
        btnCreateDemo1 = new javax.swing.JButton();
        btnViewReport = new javax.swing.JButton();
        lblDemoInfo1 = new javax.swing.JLabel();
        lblAccountInfo2 = new javax.swing.JLabel();
        btnCreateAccount2 = new javax.swing.JButton();
        btnViewAccount2 = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 1000));

        splitPane.setDividerLocation(220);

        btnViewAccount1.setBackground(new java.awt.Color(153, 255, 255));
        btnViewAccount1.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        btnViewAccount1.setText("View");
        btnViewAccount1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewAccount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAccount1ActionPerformed(evt);
            }
        });

        btnViewDemo1.setBackground(new java.awt.Color(153, 255, 255));
        btnViewDemo1.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        btnViewDemo1.setText("View");
        btnViewDemo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewDemo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDemo1ActionPerformed(evt);
            }
        });

        btnViewLicense1.setBackground(new java.awt.Color(153, 255, 255));
        btnViewLicense1.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        btnViewLicense1.setText("View");
        btnViewLicense1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewLicense1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLicense1ActionPerformed(evt);
            }
        });

        lblMedicalRecord1.setBackground(new java.awt.Color(0, 0, 0));
        lblMedicalRecord1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMedicalRecord1.setForeground(new java.awt.Color(255, 255, 255));
        lblMedicalRecord1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedicalRecord1.setText("Medical Record");
        lblMedicalRecord1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblDriversLicense1.setBackground(new java.awt.Color(0, 0, 0));
        lblDriversLicense1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDriversLicense1.setForeground(new java.awt.Color(255, 255, 255));
        lblDriversLicense1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDriversLicense1.setText("Driver's License Information");
        lblDriversLicense1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAddress1.setBackground(new java.awt.Color(0, 0, 0));
        lblAddress1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAddress1.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddress1.setText("Address Information");

        btnViewMedicalRecord1.setBackground(new java.awt.Color(153, 255, 255));
        btnViewMedicalRecord1.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        btnViewMedicalRecord1.setText("View");
        btnViewMedicalRecord1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewMedicalRecord1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMedicalRecord1ActionPerformed(evt);
            }
        });

        btnCreateAddress1.setBackground(new java.awt.Color(153, 255, 255));
        btnCreateAddress1.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        btnCreateAddress1.setText("Create");
        btnCreateAddress1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCreateAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAddress1ActionPerformed(evt);
            }
        });

        btnCreateAccount1.setBackground(new java.awt.Color(153, 255, 255));
        btnCreateAccount1.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        btnCreateAccount1.setText("Create");
        btnCreateAccount1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCreateAccount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccount1ActionPerformed(evt);
            }
        });

        lblAccountInfo1.setBackground(new java.awt.Color(0, 0, 0));
        lblAccountInfo1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAccountInfo1.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountInfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccountInfo1.setText("Checking Account Information");
        lblAccountInfo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnCreateLicense1.setBackground(new java.awt.Color(153, 255, 255));
        btnCreateLicense1.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        btnCreateLicense1.setText("Create");
        btnCreateLicense1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCreateLicense1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateLicense1ActionPerformed(evt);
            }
        });

        btnCreateMedicalRecord1.setBackground(new java.awt.Color(153, 255, 255));
        btnCreateMedicalRecord1.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        btnCreateMedicalRecord1.setText("Create");
        btnCreateMedicalRecord1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCreateMedicalRecord1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateMedicalRecord1ActionPerformed(evt);
            }
        });

        btnViewAddress1.setBackground(new java.awt.Color(153, 255, 255));
        btnViewAddress1.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        btnViewAddress1.setText("View");
        btnViewAddress1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAddress1ActionPerformed(evt);
            }
        });

        btnCreateDemo1.setBackground(new java.awt.Color(153, 255, 255));
        btnCreateDemo1.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        btnCreateDemo1.setText("Create");
        btnCreateDemo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCreateDemo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDemo1ActionPerformed(evt);
            }
        });

        btnViewReport.setBackground(new java.awt.Color(255, 102, 102));
        btnViewReport.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        btnViewReport.setText("View Report");
        btnViewReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReportActionPerformed(evt);
            }
        });

        lblDemoInfo1.setBackground(new java.awt.Color(0, 0, 0));
        lblDemoInfo1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDemoInfo1.setForeground(new java.awt.Color(255, 255, 255));
        lblDemoInfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDemoInfo1.setText("Demographic Information");
        lblDemoInfo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAccountInfo2.setBackground(new java.awt.Color(0, 0, 0));
        lblAccountInfo2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAccountInfo2.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountInfo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccountInfo2.setText("Savings Account Information");

        btnCreateAccount2.setBackground(new java.awt.Color(153, 255, 255));
        btnCreateAccount2.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        btnCreateAccount2.setText("Create");
        btnCreateAccount2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCreateAccount2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccount2ActionPerformed(evt);
            }
        });

        btnViewAccount2.setBackground(new java.awt.Color(153, 255, 255));
        btnViewAccount2.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        btnViewAccount2.setText("View");
        btnViewAccount2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewAccount2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAccount2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblDemoInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAccountInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(btnCreateAccount2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(btnViewAccount2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDriversLicense1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMedicalRecord1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(controlPanelLayout.createSequentialGroup()
                            .addComponent(btnCreateDemo1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnViewDemo1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(controlPanelLayout.createSequentialGroup()
                            .addComponent(btnCreateLicense1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnViewLicense1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(controlPanelLayout.createSequentialGroup()
                            .addComponent(btnCreateMedicalRecord1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnViewMedicalRecord1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(controlPanelLayout.createSequentialGroup()
                            .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCreateAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCreateAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnViewAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnViewAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lblAccountInfo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(lblAddress1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnViewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreateAccount1, btnCreateAccount2, btnCreateAddress1, btnCreateDemo1, btnCreateLicense1, btnCreateMedicalRecord1, btnViewAccount1, btnViewAccount2, btnViewAddress1, btnViewDemo1, btnViewLicense1, btnViewMedicalRecord1});

        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDemoInfo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateDemo1)
                    .addComponent(btnViewDemo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAddress1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewAddress1)
                    .addComponent(btnCreateAddress1))
                .addGap(18, 18, 18)
                .addComponent(lblAccountInfo2)
                .addGap(22, 22, 22)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateAccount1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewAccount1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblAccountInfo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateAccount2)
                    .addComponent(btnViewAccount2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDriversLicense1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateLicense1)
                    .addComponent(btnViewLicense1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMedicalRecord1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateMedicalRecord1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewMedicalRecord1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnViewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCreateAccount1, btnCreateAccount2, btnCreateAddress1, btnCreateDemo1, btnCreateLicense1, btnCreateMedicalRecord1, btnViewAccount1, btnViewAccount2, btnViewAddress1, btnViewDemo1, btnViewLicense1, btnViewMedicalRecord1});

        splitPane.setLeftComponent(controlPanel);

        workArea.setPreferredSize(new java.awt.Dimension(900, 631));

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 988, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateDemo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDemo1ActionPerformed
        // TODO add your handling code here:
        CreateDemographicJPanel createDemoJPanel = new CreateDemographicJPanel(demo);
        splitPane.setRightComponent(createDemoJPanel);
    }//GEN-LAST:event_btnCreateDemo1ActionPerformed

    private void btnViewDemo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDemo1ActionPerformed
        // TODO add your handling code here:
        ViewDemographicJPanel viewDemoJPanel = new ViewDemographicJPanel(demo);
        splitPane.setRightComponent(viewDemoJPanel);
    }//GEN-LAST:event_btnViewDemo1ActionPerformed

    private void btnCreateAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAddress1ActionPerformed
        // TODO add your handling code here:
        CreateAddressJPanel createAddressJPanel = new CreateAddressJPanel(address);
        splitPane.setRightComponent(createAddressJPanel);
    }//GEN-LAST:event_btnCreateAddress1ActionPerformed

    private void btnViewAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAddress1ActionPerformed
        // TODO add your handling code here:
        ViewAddressJPanel viewAddressJPanel = new ViewAddressJPanel(address);
        splitPane.setRightComponent(viewAddressJPanel);
    }//GEN-LAST:event_btnViewAddress1ActionPerformed

    private void btnCreateAccount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccount1ActionPerformed
        // TODO add your handling code here:
        CreateSavingsAccountJPanel createSavingsAccountJPanel = new CreateSavingsAccountJPanel(savingsAccInfo);
        splitPane.setRightComponent(createSavingsAccountJPanel);
        
    }//GEN-LAST:event_btnCreateAccount1ActionPerformed

    private void btnCreateLicense1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateLicense1ActionPerformed
        // TODO add your handling code here:
        CreateDriversLicenseJPanel createDriversLicenseJPanel = new CreateDriversLicenseJPanel(driversInfo);
        splitPane.setRightComponent(createDriversLicenseJPanel);
        
    }//GEN-LAST:event_btnCreateLicense1ActionPerformed

    private void btnViewLicense1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLicense1ActionPerformed
        // TODO add your handling code here:
        ViewDriversLicenseJPanel viewDriversLicenseJPanel = new ViewDriversLicenseJPanel(driversInfo);
        splitPane.setRightComponent(viewDriversLicenseJPanel);
    }//GEN-LAST:event_btnViewLicense1ActionPerformed

    private void btnCreateMedicalRecord1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateMedicalRecord1ActionPerformed
        // TODO add your handling code here:
        CreateMedicalJPanel createMedicalJPanel = new CreateMedicalJPanel(medicalRecord);
        splitPane.setRightComponent(createMedicalJPanel);
        
        
    }//GEN-LAST:event_btnCreateMedicalRecord1ActionPerformed

    private void btnViewMedicalRecord1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMedicalRecord1ActionPerformed
        // TODO add your handling code here:
        ViewMedicalJPanel viewMedicalJPanel = new ViewMedicalJPanel(medicalRecord);
        splitPane.setRightComponent(viewMedicalJPanel);
    }//GEN-LAST:event_btnViewMedicalRecord1ActionPerformed

    private void btnViewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReportActionPerformed
        // TODO add your handling code here:
        ViewFullReportJPanel viewFullReportJPanel = new ViewFullReportJPanel(demo, address, driversInfo, medicalRecord, checkingAccInfo, savingsAccInfo);
        splitPane.setRightComponent(viewFullReportJPanel);
    }//GEN-LAST:event_btnViewReportActionPerformed

    private void btnCreateAccount2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccount2ActionPerformed
        // TODO add your handling code here:
        CreateCheckingAccountJPanel createCheckingAccountJPanel = new CreateCheckingAccountJPanel(checkingAccInfo);
        splitPane.setRightComponent(createCheckingAccountJPanel);
    }//GEN-LAST:event_btnCreateAccount2ActionPerformed

    private void btnViewAccount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAccount1ActionPerformed
        // TODO add your handling code here:
        ViewSavingsAccountJPanel viewSavingsAccountJPanel = new ViewSavingsAccountJPanel(savingsAccInfo);
        splitPane.setRightComponent(viewSavingsAccountJPanel);
    }//GEN-LAST:event_btnViewAccount1ActionPerformed

    private void btnViewAccount2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAccount2ActionPerformed
        // TODO add your handling code here:
        ViewCheckingAccountJPanel viewCheckingAccountJPanel = new ViewCheckingAccountJPanel(checkingAccInfo);
        splitPane.setRightComponent(viewCheckingAccountJPanel);
    }//GEN-LAST:event_btnViewAccount2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAccount1;
    private javax.swing.JButton btnCreateAccount2;
    private javax.swing.JButton btnCreateAddress1;
    private javax.swing.JButton btnCreateDemo1;
    private javax.swing.JButton btnCreateLicense1;
    private javax.swing.JButton btnCreateMedicalRecord1;
    private javax.swing.JButton btnViewAccount1;
    private javax.swing.JButton btnViewAccount2;
    private javax.swing.JButton btnViewAddress1;
    private javax.swing.JButton btnViewDemo1;
    private javax.swing.JButton btnViewLicense1;
    private javax.swing.JButton btnViewMedicalRecord1;
    private javax.swing.JButton btnViewReport;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel lblAccountInfo1;
    private javax.swing.JLabel lblAccountInfo2;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblDemoInfo1;
    private javax.swing.JLabel lblDriversLicense1;
    private javax.swing.JLabel lblMedicalRecord1;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
