/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.SavingsAccountInformation;
import model.Address;
import model.CheckingAccountInformation;
import model.DemographicInfo;
import model.DriversLicenseInfo;
import model.MedicalRecord;

/**
 *
 * @author rtspi
 */
public class ViewFullReportJPanel extends javax.swing.JPanel {
    DemographicInfo demo;
    SavingsAccountInformation accountInformation;
    Address address;
    DriversLicenseInfo driversInfo;
    MedicalRecord medicalRecord;
    CheckingAccountInformation checkingAccInfo;
    SavingsAccountInformation savingsAccInfo;
    
    /**
     * Creates new form ViewReportJPanel
     */
    public ViewFullReportJPanel(DemographicInfo demo, Address address, DriversLicenseInfo driversInfo, MedicalRecord medicalRecord, CheckingAccountInformation checkingAccInfo, SavingsAccountInformation savingsAccInfo) {
        initComponents();
        this.demo = demo;
        this.address = address;
        this.driversInfo = driversInfo;
        this.medicalRecord = medicalRecord;
        this.checkingAccInfo = checkingAccInfo;
        this.savingsAccInfo = savingsAccInfo;
        
        
        displayFinalReport();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        lblFinalDemo = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtPhoneNum = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        lblPhoneNum = new javax.swing.JLabel();
        txtStreetAddress = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        lblZipCode = new javax.swing.JLabel();
        lblStreet = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblFinalAddress = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblLicenseNum = new javax.swing.JLabel();
        txtExpirationDate = new javax.swing.JTextField();
        txtIssueDate = new javax.swing.JTextField();
        txtBloodType = new javax.swing.JTextField();
        lblExpirationDate = new javax.swing.JLabel();
        lblIssueDate = new javax.swing.JLabel();
        lblBloodType = new javax.swing.JLabel();
        txtLicenseNum = new javax.swing.JTextField();
        lblAllergy2 = new javax.swing.JLabel();
        lblAllergy3 = new javax.swing.JLabel();
        txtRecordNum = new javax.swing.JTextField();
        txtAllergy1 = new javax.swing.JTextField();
        txtAllergy2 = new javax.swing.JTextField();
        lblFinalDriversLicense = new javax.swing.JLabel();
        txtAllergy3 = new javax.swing.JTextField();
        lblFinalMedicalRecord = new javax.swing.JLabel();
        lblRecordNum = new javax.swing.JLabel();
        lblAllergy1 = new javax.swing.JLabel();
        txtBankName1 = new javax.swing.JTextField();
        txtRoutingNum1 = new javax.swing.JTextField();
        txtAccountNum1 = new javax.swing.JTextField();
        txtAccountBal1 = new javax.swing.JTextField();
        lblBankName1 = new javax.swing.JLabel();
        lblRoutingNum1 = new javax.swing.JLabel();
        txtAccountType1 = new javax.swing.JTextField();
        lblAccountNum1 = new javax.swing.JLabel();
        lblAccountBal1 = new javax.swing.JLabel();
        lblAccountType1 = new javax.swing.JLabel();
        txtAccountBal2 = new javax.swing.JTextField();
        txtAccountType2 = new javax.swing.JTextField();
        lblBankName2 = new javax.swing.JLabel();
        lblRoutingNum2 = new javax.swing.JLabel();
        lblAccountNum2 = new javax.swing.JLabel();
        lblAccountBal2 = new javax.swing.JLabel();
        txtBankName2 = new javax.swing.JTextField();
        lblAccountType2 = new javax.swing.JLabel();
        txtRoutingNum2 = new javax.swing.JTextField();
        txtAccountNum2 = new javax.swing.JTextField();
        lblCheckingAccount = new javax.swing.JLabel();
        lblFinalSavingsAccount = new javax.swing.JLabel();

        lblFinalDemo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblFinalDemo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFinalDemo.setText("Demographic Information");

        lblFirstName.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblFirstName.setText("First Name:");

        txtSSN.setEditable(false);
        txtSSN.setBackground(new java.awt.Color(255, 255, 255));

        lblLastName.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblLastName.setText("Last Name:");

        txtLastName.setEditable(false);
        txtLastName.setBackground(new java.awt.Color(255, 255, 255));

        txtFirstName.setEditable(false);
        txtFirstName.setBackground(new java.awt.Color(255, 255, 255));

        txtDOB.setEditable(false);
        txtDOB.setBackground(new java.awt.Color(255, 255, 255));

        txtAge.setEditable(false);
        txtAge.setBackground(new java.awt.Color(255, 255, 255));

        lblAge.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblAge.setText("Age:");

        txtPhoneNum.setEditable(false);
        txtPhoneNum.setBackground(new java.awt.Color(255, 255, 255));
        txtPhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumActionPerformed(evt);
            }
        });

        lblDOB.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblDOB.setText("Date of Birth (MM/DD/YYYY):");

        lblWeight.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblWeight.setText("Weight:");

        txtHeight.setEditable(false);
        txtHeight.setBackground(new java.awt.Color(255, 255, 255));

        txtWeight.setEditable(false);
        txtWeight.setBackground(new java.awt.Color(255, 255, 255));

        lblSSN.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblSSN.setText("Social Security Number:");

        lblHeight.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblHeight.setText("Height:");

        lblPhoneNum.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblPhoneNum.setText("Phone Number:");

        txtStreetAddress.setEditable(false);
        txtStreetAddress.setBackground(new java.awt.Color(255, 255, 255));
        txtStreetAddress.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtStreetAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetAddressActionPerformed(evt);
            }
        });

        lblCity.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCity.setText("City:");

        txtZipCode.setEditable(false);
        txtZipCode.setBackground(new java.awt.Color(255, 255, 255));
        txtZipCode.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblZipCode.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblZipCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblZipCode.setText("ZipCode:");

        lblStreet.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblStreet.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStreet.setText("Street Address:");

        txtState.setEditable(false);
        txtState.setBackground(new java.awt.Color(255, 255, 255));
        txtState.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblState.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblState.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState.setText("State:");

        txtCity.setEditable(false);
        txtCity.setBackground(new java.awt.Color(255, 255, 255));
        txtCity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblFinalAddress.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblFinalAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFinalAddress.setText("Address");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo (1).jpg"))); // NOI18N

        lblLicenseNum.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblLicenseNum.setText("License Number:");

        txtExpirationDate.setEditable(false);
        txtExpirationDate.setBackground(new java.awt.Color(255, 255, 255));

        txtIssueDate.setEditable(false);
        txtIssueDate.setBackground(new java.awt.Color(255, 255, 255));

        txtBloodType.setEditable(false);
        txtBloodType.setBackground(new java.awt.Color(255, 255, 255));

        lblExpirationDate.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblExpirationDate.setText("Expiration Date:");

        lblIssueDate.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblIssueDate.setText("Issue Date:");

        lblBloodType.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblBloodType.setText("Blood Type:");

        txtLicenseNum.setEditable(false);
        txtLicenseNum.setBackground(new java.awt.Color(255, 255, 255));

        lblAllergy2.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblAllergy2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAllergy2.setText("Allergy 2:");

        lblAllergy3.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblAllergy3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAllergy3.setText("Allergy 3:");

        txtRecordNum.setEditable(false);
        txtRecordNum.setBackground(new java.awt.Color(255, 255, 255));
        txtRecordNum.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRecordNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecordNumActionPerformed(evt);
            }
        });

        txtAllergy1.setEditable(false);
        txtAllergy1.setBackground(new java.awt.Color(255, 255, 255));
        txtAllergy1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtAllergy2.setEditable(false);
        txtAllergy2.setBackground(new java.awt.Color(255, 255, 255));
        txtAllergy2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblFinalDriversLicense.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblFinalDriversLicense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFinalDriversLicense.setText("Driver's License");

        txtAllergy3.setEditable(false);
        txtAllergy3.setBackground(new java.awt.Color(255, 255, 255));
        txtAllergy3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblFinalMedicalRecord.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblFinalMedicalRecord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFinalMedicalRecord.setText("Medical Record");

        lblRecordNum.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblRecordNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecordNum.setText("Medical Record Number:");

        lblAllergy1.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblAllergy1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAllergy1.setText("Allergy 1:");

        txtBankName1.setEditable(false);
        txtBankName1.setBackground(new java.awt.Color(255, 255, 255));
        txtBankName1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBankName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankName1ActionPerformed(evt);
            }
        });

        txtRoutingNum1.setEditable(false);
        txtRoutingNum1.setBackground(new java.awt.Color(255, 255, 255));
        txtRoutingNum1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtAccountNum1.setEditable(false);
        txtAccountNum1.setBackground(new java.awt.Color(255, 255, 255));
        txtAccountNum1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtAccountBal1.setEditable(false);
        txtAccountBal1.setBackground(new java.awt.Color(255, 255, 255));
        txtAccountBal1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAccountBal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountBal1ActionPerformed(evt);
            }
        });

        lblBankName1.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblBankName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBankName1.setText("Bank Name:");

        lblRoutingNum1.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblRoutingNum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRoutingNum1.setText("Routing Number:");

        txtAccountType1.setEditable(false);
        txtAccountType1.setBackground(new java.awt.Color(255, 255, 255));
        txtAccountType1.setFont(new java.awt.Font("Calibri", 2, 11)); // NOI18N
        txtAccountType1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAccountType1.setText("Savings Account");
        txtAccountType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountType1ActionPerformed(evt);
            }
        });

        lblAccountNum1.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblAccountNum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccountNum1.setText("Account Number:");

        lblAccountBal1.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblAccountBal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccountBal1.setText("Account Balance:");

        lblAccountType1.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblAccountType1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccountType1.setText("Account Type:");

        txtAccountBal2.setEditable(false);
        txtAccountBal2.setBackground(new java.awt.Color(255, 255, 255));
        txtAccountBal2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtAccountType2.setEditable(false);
        txtAccountType2.setBackground(new java.awt.Color(255, 255, 255));
        txtAccountType2.setFont(new java.awt.Font("Calibri", 2, 11)); // NOI18N
        txtAccountType2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAccountType2.setText("Checking Account");
        txtAccountType2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountType2ActionPerformed(evt);
            }
        });

        lblBankName2.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblBankName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBankName2.setText("Bank Name:");

        lblRoutingNum2.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblRoutingNum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRoutingNum2.setText("Routing Number:");

        lblAccountNum2.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblAccountNum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccountNum2.setText("Account Number:");

        lblAccountBal2.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblAccountBal2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccountBal2.setText("Account Balance:");

        txtBankName2.setEditable(false);
        txtBankName2.setBackground(new java.awt.Color(255, 255, 255));
        txtBankName2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblAccountType2.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblAccountType2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccountType2.setText("Account Type:");

        txtRoutingNum2.setEditable(false);
        txtRoutingNum2.setBackground(new java.awt.Color(255, 255, 255));
        txtRoutingNum2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtAccountNum2.setEditable(false);
        txtAccountNum2.setBackground(new java.awt.Color(255, 255, 255));
        txtAccountNum2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblCheckingAccount.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCheckingAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCheckingAccount.setText("Bank Account Information (Checking)");

        lblFinalSavingsAccount.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblFinalSavingsAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFinalSavingsAccount.setText("Bank Account Information (Savings)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLastName)
                                    .addComponent(lblPhoneNum)
                                    .addComponent(lblDOB)
                                    .addComponent(lblAge)
                                    .addComponent(lblHeight)
                                    .addComponent(lblWeight)
                                    .addComponent(lblSSN)
                                    .addComponent(lblFirstName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHeight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhoneNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDOB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblFinalDemo, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblState)
                                            .addComponent(lblZipCode)
                                            .addComponent(lblCity)
                                            .addComponent(lblStreet))
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtZipCode, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtCity, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtState, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblFinalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLicenseNum)
                                    .addComponent(lblExpirationDate)
                                    .addComponent(lblIssueDate)
                                    .addComponent(lblBloodType))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtExpirationDate)
                                    .addComponent(txtIssueDate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLicenseNum, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblFinalDriversLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRecordNum)
                                    .addComponent(lblAllergy1)
                                    .addComponent(lblAllergy2)
                                    .addComponent(lblAllergy3))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAllergy3)
                                    .addComponent(txtAllergy2)
                                    .addComponent(txtAllergy1)
                                    .addComponent(txtRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(lblFinalMedicalRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBankName1)
                            .addComponent(lblRoutingNum1)
                            .addComponent(lblAccountNum1)
                            .addComponent(lblAccountBal1)
                            .addComponent(lblAccountType1))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAccountBal1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAccountNum1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRoutingNum1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBankName1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAccountType1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAccountType2)
                            .addComponent(lblAccountNum2)
                            .addComponent(lblRoutingNum2)
                            .addComponent(lblAccountBal2)
                            .addComponent(lblBankName2))
                        .addGap(104, 104, 104)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRoutingNum2)
                            .addComponent(txtBankName2)
                            .addComponent(txtAccountNum2)
                            .addComponent(txtAccountBal2)
                            .addComponent(txtAccountType2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblFinalSavingsAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCheckingAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAccountBal1, txtAccountBal2, txtAccountNum1, txtAccountNum2, txtAccountType1, txtAccountType2, txtAge, txtAllergy1, txtAllergy2, txtAllergy3, txtBankName1, txtBankName2, txtBloodType, txtCity, txtDOB, txtExpirationDate, txtFirstName, txtHeight, txtIssueDate, txtLastName, txtLicenseNum, txtPhoneNum, txtRecordNum, txtRoutingNum1, txtRoutingNum2, txtSSN, txtState, txtWeight, txtZipCode});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblFinalAddress)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStreet)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCity))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblState))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblZipCode))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblFinalDemo)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFirstName))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastName))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhoneNum)
                            .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDOB)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHeight)
                            .addComponent(txtPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWeight)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSSN)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFinalMedicalRecord)
                    .addComponent(lblFinalDriversLicense, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLicenseNum))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblRecordNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIssueDate)
                            .addComponent(lblAllergy1))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblExpirationDate)
                            .addComponent(lblAllergy2))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBloodType)
                            .addComponent(lblAllergy3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtAllergy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtAllergy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtAllergy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFinalSavingsAccount)
                            .addComponent(lblCheckingAccount))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBankName1)
                            .addComponent(txtBankName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRoutingNum1)
                            .addComponent(txtRoutingNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAccountNum1)
                            .addComponent(txtAccountNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAccountBal1)
                            .addComponent(txtAccountBal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAccountType1)
                            .addComponent(txtAccountType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblBankName2)
                            .addGap(18, 18, 18)
                            .addComponent(lblRoutingNum2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(txtBankName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(txtRoutingNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAccountNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAccountNum2))
                            .addGap(10, 10, 10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAccountBal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAccountBal2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAccountType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAccountType2)))))
                .addContainerGap(342, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAccountBal1, txtAccountBal2, txtAccountNum1, txtAccountNum2, txtAccountType1, txtAccountType2, txtAge, txtAllergy1, txtAllergy2, txtAllergy3, txtBankName1, txtBankName2, txtBloodType, txtCity, txtDOB, txtExpirationDate, txtFirstName, txtHeight, txtIssueDate, txtLastName, txtLicenseNum, txtPhoneNum, txtRecordNum, txtRoutingNum1, txtRoutingNum2, txtSSN, txtState, txtWeight, txtZipCode});

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumActionPerformed

    private void txtStreetAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetAddressActionPerformed

    private void txtRecordNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecordNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecordNumActionPerformed

    private void txtBankName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankName1ActionPerformed

    private void txtAccountBal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountBal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountBal1ActionPerformed

    private void txtAccountType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountType1ActionPerformed

    private void txtAccountType2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountType2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountType2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAccountBal1;
    private javax.swing.JLabel lblAccountBal2;
    private javax.swing.JLabel lblAccountNum1;
    private javax.swing.JLabel lblAccountNum2;
    private javax.swing.JLabel lblAccountType1;
    private javax.swing.JLabel lblAccountType2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAllergy1;
    private javax.swing.JLabel lblAllergy2;
    private javax.swing.JLabel lblAllergy3;
    private javax.swing.JLabel lblBankName1;
    private javax.swing.JLabel lblBankName2;
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblCheckingAccount;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblExpirationDate;
    private javax.swing.JLabel lblFinalAddress;
    private javax.swing.JLabel lblFinalDemo;
    private javax.swing.JLabel lblFinalDriversLicense;
    private javax.swing.JLabel lblFinalMedicalRecord;
    private javax.swing.JLabel lblFinalSavingsAccount;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblIssueDate;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLicenseNum;
    private javax.swing.JLabel lblPhoneNum;
    private javax.swing.JLabel lblRecordNum;
    private javax.swing.JLabel lblRoutingNum1;
    private javax.swing.JLabel lblRoutingNum2;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JTextField txtAccountBal1;
    private javax.swing.JTextField txtAccountBal2;
    private javax.swing.JTextField txtAccountNum1;
    private javax.swing.JTextField txtAccountNum2;
    private javax.swing.JTextField txtAccountType1;
    private javax.swing.JTextField txtAccountType2;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAllergy1;
    private javax.swing.JTextField txtAllergy2;
    private javax.swing.JTextField txtAllergy3;
    private javax.swing.JTextField txtBankName1;
    private javax.swing.JTextField txtBankName2;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtExpirationDate;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtIssueDate;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLicenseNum;
    private javax.swing.JTextField txtPhoneNum;
    private javax.swing.JTextField txtRecordNum;
    private javax.swing.JTextField txtRoutingNum1;
    private javax.swing.JTextField txtRoutingNum2;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreetAddress;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables

    private void displayFinalReport() {
        txtFirstName.setText(demo.getFirstName());
        txtLastName.setText(demo.getLastName());
        txtPhoneNum.setText(demo.getPhoneNum());
        txtDOB.setText(demo.getDOB());
        txtAge.setText(demo.getAge());
        txtHeight.setText(demo.getHeight());
        txtWeight.setText(demo.getWeight());
        txtSSN.setText(demo.getSSN());
        
        txtStreetAddress.setText(address.getStreetAddress());
        txtCity.setText(address.getCity());
        txtState.setText(address.getState());
        txtZipCode.setText(address.getZipCode());
        
        txtLicenseNum.setText(driversInfo.getLicenseNum());
        txtIssueDate.setText(driversInfo.getIssueDate());
        txtExpirationDate.setText(driversInfo.getExpirationDate());
        txtBloodType.setText(driversInfo.getBloodType());
        
        txtRecordNum.setText(medicalRecord.getMedicalRecordNum());
        txtAllergy1.setText(medicalRecord.getAllergy1());
        txtAllergy2.setText(medicalRecord.getAllergy2());
        txtAllergy3.setText(medicalRecord.getAllergy3());
        
        txtBankName1.setText(savingsAccInfo.getBankName());
        txtAccountNum1.setText(savingsAccInfo.getAccountNum());
        txtRoutingNum1.setText(savingsAccInfo.getRoutingNum());
        txtAccountBal1.setText(savingsAccInfo.getAccountBal());
        
        txtBankName2.setText(checkingAccInfo.getBankName());
        txtAccountNum2.setText(checkingAccInfo.getAccountNum());
        txtRoutingNum2.setText(checkingAccInfo.getRoutingNum());
        txtAccountBal2.setText(checkingAccInfo.getAccountBal());
    }
}
    

