/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.CheckingAccountInformation;

/**
 *
 * @author rtspi
 */
public class ViewCheckingAccountJPanel extends javax.swing.JPanel {
    
    CheckingAccountInformation checkingAccInfo;
    /**
     * Creates new form ViewCheckingAccountJPanel
     */
    public ViewCheckingAccountJPanel(CheckingAccountInformation checkingAccInfo) {
        initComponents();
        this.checkingAccInfo = checkingAccInfo;
        
        displayCheckingAccInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBankName2 = new javax.swing.JTextField();
        txtRoutingNum2 = new javax.swing.JTextField();
        txtAccountNum2 = new javax.swing.JTextField();
        lblChecking = new javax.swing.JLabel();
        txtAccountBal2 = new javax.swing.JTextField();
        txtAccountType2 = new javax.swing.JTextField();
        lblBankName2 = new javax.swing.JLabel();
        lblRoutingNum2 = new javax.swing.JLabel();
        lblAccountNum2 = new javax.swing.JLabel();
        lblAccountBal2 = new javax.swing.JLabel();
        lblAccountType2 = new javax.swing.JLabel();

        txtBankName2.setEditable(false);
        txtBankName2.setBackground(new java.awt.Color(255, 255, 255));
        txtBankName2.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N

        txtRoutingNum2.setEditable(false);
        txtRoutingNum2.setBackground(new java.awt.Color(255, 255, 255));
        txtRoutingNum2.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N

        txtAccountNum2.setEditable(false);
        txtAccountNum2.setBackground(new java.awt.Color(255, 255, 255));
        txtAccountNum2.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N

        lblChecking.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblChecking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChecking.setText("View Checking Account Information");

        txtAccountBal2.setEditable(false);
        txtAccountBal2.setBackground(new java.awt.Color(255, 255, 255));
        txtAccountBal2.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N

        txtAccountType2.setEditable(false);
        txtAccountType2.setBackground(new java.awt.Color(255, 255, 255));
        txtAccountType2.setFont(new java.awt.Font("Calibri", 2, 11)); // NOI18N
        txtAccountType2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblBankName2.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblBankName2.setText("Bank Name:");

        lblRoutingNum2.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblRoutingNum2.setText("Routing Number:");

        lblAccountNum2.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblAccountNum2.setText("Account Number:");

        lblAccountBal2.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblAccountBal2.setText("Account Balance:");

        lblAccountType2.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblAccountType2.setText("Account Type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblChecking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBankName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRoutingNum2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(lblAccountNum2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAccountBal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAccountType2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16)))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAccountType2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(txtAccountBal2)
                    .addComponent(txtAccountNum2)
                    .addComponent(txtRoutingNum2)
                    .addComponent(txtBankName2))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblChecking)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBankName2)
                            .addComponent(txtBankName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRoutingNum2)
                            .addComponent(txtRoutingNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(lblAccountNum2)
                        .addGap(18, 18, 18)
                        .addComponent(lblAccountBal2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAccountNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAccountBal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountType2)
                    .addComponent(txtAccountType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAccountBal2;
    private javax.swing.JLabel lblAccountNum2;
    private javax.swing.JLabel lblAccountType2;
    private javax.swing.JLabel lblBankName2;
    private javax.swing.JLabel lblChecking;
    private javax.swing.JLabel lblRoutingNum2;
    private javax.swing.JTextField txtAccountBal2;
    private javax.swing.JTextField txtAccountNum2;
    private javax.swing.JTextField txtAccountType2;
    private javax.swing.JTextField txtBankName2;
    private javax.swing.JTextField txtRoutingNum2;
    // End of variables declaration//GEN-END:variables

    private void displayCheckingAccInfo() {
        
        txtBankName2.setText(checkingAccInfo.getBankName());
        txtAccountNum2.setText(checkingAccInfo.getAccountNum());
        txtRoutingNum2.setText(checkingAccInfo.getRoutingNum());
        txtAccountBal2.setText(checkingAccInfo.getAccountBal());
    }
}
