/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.DriversLicenseInfo;

/**
 *
 * @author rtspi
 */
public class ViewDriversLicenseJPanel extends javax.swing.JPanel {
    
    DriversLicenseInfo driversInfo;
    /**
     * Creates new form ViewDriversLicenseJPanel
     */
    public ViewDriversLicenseJPanel(DriversLicenseInfo driversInfo) {
        initComponents();
        this.driversInfo = driversInfo;
        
        displayDriversInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDriversLicense = new javax.swing.JLabel();
        txtIssueDate = new javax.swing.JTextField();
        txtBloodType = new javax.swing.JTextField();
        lblExpirationDate = new javax.swing.JLabel();
        lblIssueDate = new javax.swing.JLabel();
        lblBloodType = new javax.swing.JLabel();
        txtLicenseNum = new javax.swing.JTextField();
        lblLicenseNum = new javax.swing.JLabel();
        txtExpirationDate = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(500, 350));

        lblDriversLicense.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblDriversLicense.setText("                                        View Driver's License Information");

        txtIssueDate.setEditable(false);
        txtIssueDate.setBackground(new java.awt.Color(255, 255, 255));

        txtBloodType.setEditable(false);
        txtBloodType.setBackground(new java.awt.Color(255, 255, 255));

        lblExpirationDate.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblExpirationDate.setText("Expiration Date:");

        lblIssueDate.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblIssueDate.setText("Issue Date:");

        lblBloodType.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblBloodType.setText("Blood Type:");

        txtLicenseNum.setEditable(false);
        txtLicenseNum.setBackground(new java.awt.Color(255, 255, 255));

        lblLicenseNum.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        lblLicenseNum.setText("License Number:");

        txtExpirationDate.setEditable(false);
        txtExpirationDate.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLicenseNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIssueDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addComponent(lblExpirationDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBloodType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22)))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBloodType, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(txtExpirationDate, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(txtIssueDate, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(txtLicenseNum, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addGap(69, 69, 69))
            .addComponent(lblDriversLicense, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblDriversLicense)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicenseNum)
                    .addComponent(txtLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIssueDate)
                    .addComponent(txtIssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExpirationDate))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBloodType)
                    .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblDriversLicense;
    private javax.swing.JLabel lblExpirationDate;
    private javax.swing.JLabel lblIssueDate;
    private javax.swing.JLabel lblLicenseNum;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JTextField txtExpirationDate;
    private javax.swing.JTextField txtIssueDate;
    private javax.swing.JTextField txtLicenseNum;
    // End of variables declaration//GEN-END:variables

    private void displayDriversInfo() {
        txtLicenseNum.setText(driversInfo.getLicenseNum());
        txtIssueDate.setText(driversInfo.getIssueDate());
        txtExpirationDate.setText(driversInfo.getExpirationDate());
        txtBloodType.setText(driversInfo.getBloodType());
        
    }
}
